"""Tests for Phase 3 encoder classifier and LoRA trainer.

GPU-dependent tests are mocked.  All tests here run on CPU without models downloaded.
"""

from __future__ import annotations

import json
from pathlib import Path
from unittest.mock import MagicMock

import numpy as np
import pytest
import torch

# ======================================================================
# EncoderResult Tests
# ======================================================================


class TestEncoderResult:
    def test_basic_creation(self):
        from aigc_detector.detection.encoder import EncoderResult

        r = EncoderResult(label="ai", p_ai=0.92, confidence=0.92, model_name="test-model")
        assert r.label == "ai"
        assert r.p_ai == 0.92
        assert r.confidence == 0.92
        assert r.model_name == "test-model"

    def test_to_dict(self):
        from aigc_detector.detection.encoder import EncoderResult

        r = EncoderResult(label="human", p_ai=0.3, confidence=0.7, model_name="deberta-v3")
        d = r.to_dict()
        assert d["label"] == "human"
        assert d["p_ai"] == 0.3
        assert d["confidence"] == 0.7
        assert d["model_name"] == "deberta-v3"
        assert len(d) == 4

    def test_human_label(self):
        from aigc_detector.detection.encoder import EncoderResult

        r = EncoderResult(label="human", p_ai=0.1, confidence=0.9, model_name="m")
        assert r.label == "human"
        assert r.confidence == 0.9


# ======================================================================
# EncoderClassifier Tests
# ======================================================================


class TestEncoderClassifier:
    def test_default_init(self):
        from aigc_detector.detection.encoder import EncoderClassifier

        clf = EncoderClassifier()
        assert clf.base_model_name == "microsoft/deberta-v3-large"
        assert clf.device == "cuda"
        assert clf.max_length == 512
        assert clf.num_labels == 2
        assert not clf.is_loaded

    def test_custom_init(self):
        from aigc_detector.detection.encoder import EncoderClassifier

        clf = EncoderClassifier(
            base_model_name="hfl/chinese-roberta-wwm-ext-large",
            adapter_path="/tmp/adapter",
            device="cpu",
            max_length=256,
        )
        assert clf.base_model_name == "hfl/chinese-roberta-wwm-ext-large"
        assert clf.adapter_path == Path("/tmp/adapter")
        assert clf.device == "cpu"
        assert clf.max_length == 256

    def test_adapter_path_none(self):
        from aigc_detector.detection.encoder import EncoderClassifier

        clf = EncoderClassifier(adapter_path=None)
        assert clf.adapter_path is None

    def test_not_loaded_raises(self):
        from aigc_detector.detection.encoder import EncoderClassifier

        clf = EncoderClassifier()
        with pytest.raises(RuntimeError, match="Model not loaded"):
            clf.predict("test text")

    def test_predict_with_threshold_not_loaded_raises(self):
        from aigc_detector.detection.encoder import EncoderClassifier

        clf = EncoderClassifier()
        with pytest.raises(RuntimeError, match="Model not loaded"):
            clf.predict_with_threshold("test text", threshold=0.6)

    def test_label_map(self):
        from aigc_detector.detection.encoder import EncoderClassifier

        assert EncoderClassifier.LABEL_MAP == {0: "human", 1: "ai"}

    def test_predict_with_mock_ai(self):
        from aigc_detector.detection.encoder import EncoderClassifier

        clf = EncoderClassifier(device="cpu")

        # Mock model: logits favor class 1 (AI)
        mock_model = MagicMock()
        mock_model.return_value = MagicMock(logits=torch.tensor([[0.1, 2.5]]))

        mock_tokenizer = MagicMock()
        mock_tokenizer.return_value = {
            "input_ids": torch.tensor([[1, 2, 3]]),
            "attention_mask": torch.tensor([[1, 1, 1]]),
        }

        clf._model = mock_model
        clf._tokenizer = mock_tokenizer

        result = clf.predict("This text was generated by AI.")
        assert result.label == "ai"
        assert result.p_ai > 0.5
        assert result.confidence > 0.5
        assert result.model_name == "microsoft/deberta-v3-large"

    def test_predict_with_mock_human(self):
        from aigc_detector.detection.encoder import EncoderClassifier

        clf = EncoderClassifier(device="cpu")

        # Mock model: logits favor class 0 (human)
        mock_model = MagicMock()
        mock_model.return_value = MagicMock(logits=torch.tensor([[2.5, 0.1]]))

        mock_tokenizer = MagicMock()
        mock_tokenizer.return_value = {
            "input_ids": torch.tensor([[1, 2, 3]]),
            "attention_mask": torch.tensor([[1, 1, 1]]),
        }

        clf._model = mock_model
        clf._tokenizer = mock_tokenizer

        result = clf.predict("This is human written text.")
        assert result.label == "human"
        assert result.p_ai < 0.5
        assert result.confidence > 0.5

    def test_predict_batch(self):
        from aigc_detector.detection.encoder import EncoderClassifier

        clf = EncoderClassifier(device="cpu")

        mock_model = MagicMock()
        mock_model.return_value = MagicMock(logits=torch.tensor([[0.1, 2.0]]))

        mock_tokenizer = MagicMock()
        mock_tokenizer.return_value = {
            "input_ids": torch.tensor([[1, 2, 3]]),
            "attention_mask": torch.tensor([[1, 1, 1]]),
        }

        clf._model = mock_model
        clf._tokenizer = mock_tokenizer

        results = clf.predict_batch(["text 1", "text 2", "text 3"])
        assert len(results) == 3
        for r in results:
            assert r.label in ("ai", "human")

    def test_predict_proba(self):
        from aigc_detector.detection.encoder import EncoderClassifier

        clf = EncoderClassifier(device="cpu")

        mock_model = MagicMock()
        mock_model.return_value = MagicMock(logits=torch.tensor([[0.5, 1.5]]))

        mock_tokenizer = MagicMock()
        mock_tokenizer.return_value = {
            "input_ids": torch.tensor([[1, 2]]),
            "attention_mask": torch.tensor([[1, 1]]),
        }

        clf._model = mock_model
        clf._tokenizer = mock_tokenizer

        p = clf.predict_proba("test")
        assert isinstance(p, float)
        assert 0.0 <= p <= 1.0

    def test_predict_with_threshold(self):
        from aigc_detector.detection.encoder import EncoderClassifier

        clf = EncoderClassifier(device="cpu")

        mock_model = MagicMock()
        # p_ai will be softmax([0.5, 1.0])[1] ≈ 0.62
        mock_model.return_value = MagicMock(logits=torch.tensor([[0.5, 1.0]]))

        mock_tokenizer = MagicMock()
        mock_tokenizer.return_value = {
            "input_ids": torch.tensor([[1, 2]]),
            "attention_mask": torch.tensor([[1, 1]]),
        }

        clf._model = mock_model
        clf._tokenizer = mock_tokenizer

        # With default threshold 0.5, should be "ai"
        r1 = clf.predict_with_threshold("test", threshold=0.5)
        assert r1.label == "ai"

        # With high threshold 0.9, should be "human"
        r2 = clf.predict_with_threshold("test", threshold=0.9)
        assert r2.label == "human"

    def test_unload(self):
        from aigc_detector.detection.encoder import EncoderClassifier

        clf = EncoderClassifier(device="cpu")
        clf._model = MagicMock()
        clf._tokenizer = MagicMock()
        assert clf.is_loaded
        clf.unload()
        assert not clf.is_loaded
        assert clf._model is None
        assert clf._tokenizer is None

    def test_load_idempotent(self):
        """Calling load() when already loaded should be a no-op."""
        from aigc_detector.detection.encoder import EncoderClassifier

        clf = EncoderClassifier(device="cpu")
        mock_model = MagicMock()
        clf._model = mock_model
        clf._tokenizer = MagicMock()

        # load() should not replace the existing model
        clf.load()
        assert clf._model is mock_model


# ======================================================================
# TrainerConfig Tests
# ======================================================================


class TestTrainerConfig:
    def test_default_values(self):
        from aigc_detector.training.trainer import TrainerConfig

        cfg = TrainerConfig()
        assert cfg.base_model == "microsoft/deberta-v3-large"
        assert cfg.num_labels == 2
        assert cfg.lora_r == 16
        assert cfg.lora_alpha == 32
        assert cfg.lora_dropout == 0.1
        assert cfg.batch_size == 16
        assert cfg.learning_rate == 2e-5
        assert cfg.num_epochs == 3
        assert cfg.fp16 is True
        assert cfg.seed == 42
        assert cfg.label_map == {"human": 0, "ai": 1}

    def test_custom_values(self):
        from aigc_detector.training.trainer import TrainerConfig

        cfg = TrainerConfig(
            base_model="hfl/chinese-roberta-wwm-ext-large",
            lora_r=8,
            batch_size=8,
            num_epochs=5,
        )
        assert cfg.base_model == "hfl/chinese-roberta-wwm-ext-large"
        assert cfg.lora_r == 8
        assert cfg.batch_size == 8
        assert cfg.num_epochs == 5


class TestLoadTrainerConfig:
    def test_load_en_config(self):
        from aigc_detector.training.trainer import load_trainer_config

        cfg = load_trainer_config("configs/training.yaml", language="en")
        assert cfg.base_model == "microsoft/deberta-v3-large"
        assert cfg.lora_r == 16
        assert cfg.lora_alpha == 32
        assert "query_proj" in cfg.target_modules
        assert "value_proj" in cfg.target_modules
        assert cfg.output_dir == "models/encoder-en"

    def test_load_zh_config(self):
        from aigc_detector.training.trainer import load_trainer_config

        cfg = load_trainer_config("configs/training.yaml", language="zh")
        assert cfg.base_model == "hfl/chinese-roberta-wwm-ext-large"
        assert "query" in cfg.target_modules
        assert "value" in cfg.target_modules
        assert cfg.output_dir == "models/encoder-zh"

    def test_training_params_from_yaml(self):
        from aigc_detector.training.trainer import load_trainer_config

        cfg = load_trainer_config("configs/training.yaml", language="en")
        assert cfg.num_epochs == 3
        assert cfg.batch_size == 16
        assert cfg.eval_batch_size == 32
        assert cfg.learning_rate == 2e-5
        assert cfg.warmup_ratio == 0.1
        assert cfg.fp16 is True
        assert cfg.max_length == 512

    def test_data_config_from_yaml(self):
        from aigc_detector.training.trainer import load_trainer_config

        cfg = load_trainer_config("configs/training.yaml", language="en")
        assert cfg.train_path == "dataset/processed/train.jsonl"
        assert cfg.val_path == "dataset/processed/val.jsonl"
        assert cfg.text_key == "text"
        assert cfg.label_key == "label"
        assert cfg.label_map == {"human": 0, "ai": 1}


# ======================================================================
# TextClassificationDataset Tests
# ======================================================================


class TestTextClassificationDataset:
    def test_load_from_jsonl(self, tmp_path):
        from aigc_detector.training.trainer import TextClassificationDataset

        records = [
            {"text": "Human written text about science.", "label": "human"},
            {"text": "AI generated content about technology.", "label": "ai"},
            {"text": "Another human text about history.", "label": "human"},
            {"text": "Mixed content example.", "label": "mixed"},  # should be skipped
        ]
        path = tmp_path / "data.jsonl"
        with open(path, "w") as f:
            for r in records:
                f.write(json.dumps(r) + "\n")

        mock_tokenizer = MagicMock()
        ds = TextClassificationDataset(path, mock_tokenizer)
        assert len(ds) == 3  # "mixed" is skipped
        assert ds.labels == [0, 1, 0]  # human=0, ai=1

    def test_file_not_found(self, tmp_path):
        from aigc_detector.training.trainer import TextClassificationDataset

        mock_tokenizer = MagicMock()
        with pytest.raises(FileNotFoundError, match="Dataset file not found"):
            TextClassificationDataset(tmp_path / "nonexistent.jsonl", mock_tokenizer)

    def test_getitem_returns_dict(self, tmp_path):
        from aigc_detector.training.trainer import TextClassificationDataset

        records = [
            {"text": "Test text one.", "label": "human"},
            {"text": "Test text two.", "label": "ai"},
        ]
        path = tmp_path / "data.jsonl"
        with open(path, "w") as f:
            for r in records:
                f.write(json.dumps(r) + "\n")

        mock_tokenizer = MagicMock()
        mock_tokenizer.return_value = {
            "input_ids": torch.ones(1, 512, dtype=torch.long),
            "attention_mask": torch.ones(1, 512, dtype=torch.long),
        }

        ds = TextClassificationDataset(path, mock_tokenizer, max_length=512)
        item = ds[0]
        assert "input_ids" in item
        assert "attention_mask" in item
        assert "labels" in item
        assert item["labels"].dtype == torch.long
        assert item["labels"].item() == 0  # human

    def test_custom_keys(self, tmp_path):
        from aigc_detector.training.trainer import TextClassificationDataset

        records = [
            {"content": "Some text.", "tag": "human"},
            {"content": "More text.", "tag": "ai"},
        ]
        path = tmp_path / "custom.jsonl"
        with open(path, "w") as f:
            for r in records:
                f.write(json.dumps(r) + "\n")

        mock_tokenizer = MagicMock()
        ds = TextClassificationDataset(path, mock_tokenizer, text_key="content", label_key="tag")
        assert len(ds) == 2
        assert ds.texts == ["Some text.", "More text."]


# ======================================================================
# compute_metrics Tests
# ======================================================================


class TestComputeMetrics:
    def test_perfect_predictions(self):
        from aigc_detector.training.trainer import compute_metrics

        logits = np.array([[2.0, 0.1], [0.1, 2.0], [2.0, 0.1], [0.1, 2.0]])
        labels = np.array([0, 1, 0, 1])
        result = compute_metrics((logits, labels))
        assert result["accuracy"] == 1.0
        assert result["f1"] == 1.0

    def test_mixed_predictions(self):
        from aigc_detector.training.trainer import compute_metrics

        logits = np.array([[2.0, 0.1], [2.0, 0.1], [0.1, 2.0], [0.1, 2.0]])
        labels = np.array([0, 1, 0, 1])
        result = compute_metrics((logits, labels))
        assert result["accuracy"] == 0.5

    def test_all_same_class(self):
        from aigc_detector.training.trainer import compute_metrics

        logits = np.array([[2.0, 0.1], [2.0, 0.1]])
        labels = np.array([0, 0])
        result = compute_metrics((logits, labels))
        assert result["accuracy"] == 1.0
        assert result["f1"] == 0.0  # no positive class predicted


# ======================================================================
# LoRATrainer Tests
# ======================================================================


class TestLoRATrainer:
    def test_init(self):
        from aigc_detector.training.trainer import LoRATrainer, TrainerConfig

        cfg = TrainerConfig()
        trainer = LoRATrainer(cfg, device="cpu")
        assert trainer.config is cfg
        assert trainer.device == "cpu"
        assert trainer._model is None
        assert trainer._tokenizer is None
        assert trainer._trainer is None

    def test_save_adapter_not_initialized_raises(self):
        from aigc_detector.training.trainer import LoRATrainer, TrainerConfig

        cfg = TrainerConfig()
        trainer = LoRATrainer(cfg)
        with pytest.raises(RuntimeError, match="No model to save"):
            trainer.save_adapter("/tmp/test")

    def test_evaluate_not_initialized_raises(self):
        from aigc_detector.training.trainer import LoRATrainer, TrainerConfig

        cfg = TrainerConfig()
        trainer = LoRATrainer(cfg)
        with pytest.raises(RuntimeError, match="Trainer not initialised"):
            trainer.evaluate()

    def test_cleanup(self):
        from aigc_detector.training.trainer import LoRATrainer, TrainerConfig

        cfg = TrainerConfig()
        trainer = LoRATrainer(cfg, device="cpu")
        trainer._model = MagicMock()
        trainer._tokenizer = MagicMock()
        trainer._trainer = MagicMock()

        trainer.cleanup()
        assert trainer._model is None
        assert trainer._tokenizer is None
        assert trainer._trainer is None

    def test_save_adapter_with_mock(self, tmp_path):
        from aigc_detector.training.trainer import LoRATrainer, TrainerConfig

        cfg = TrainerConfig()
        trainer = LoRATrainer(cfg)
        trainer._model = MagicMock()

        adapter_path = tmp_path / "adapter"
        trainer.save_adapter(adapter_path)
        trainer._model.save_pretrained.assert_called_once_with(str(adapter_path))
